name: flutter_base
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Package
  package_info: ^2.0.2

  #UI
  getwidget: ^2.0.3
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.7
  carousel_slider: ^4.0.0
  modal_bottom_sheet: ^2.0.0

  #Alarm
  flash: ^2.0.1

  #Launcher
  url_launcher: ^6.0.7

  #Loading
  skeleton_text: ^3.0.0
  shimmer: ^2.0.0
  flutter_spinkit: ^5.0.0

  #Animation
  page_transition: ^2.0.2
  simple_animations: ^3.1.1
  animations: ^2.0.0

  #Image
  flutter_svg: ^0.22.0
  photo_view: ^0.11.1

  #Fonts
  google_fonts: ^2.1.0

  #Text
  auto_size_text: ^2.1.0
  readmore: ^2.1.0
  marquee: ^2.2.0
  recase: ^4.0.0

  #Datetime
  syncfusion_flutter_datepicker: ^19.1.69-beta

  #Chart
  syncfusion_flutter_charts: ^19.1.69+1

  #Size
  sizer: ^2.0.13

  #Map
  vtmap_gl: ^1.1.11
  location: ^4.3.0

  #Permission
  super_easy_permissions: ^0.0.6
  
  #File
  dio: ^4.0.0
  open_file: ^3.2.1
  # ext_storage: ^1.0.3
  share: ^2.0.4

  #Webview
  flutter_webview_plugin: ^0.4.0

  #List/Loadmore
  pull_to_refresh: ^2.0.0

  #Notification popup
  flutter_local_notifications: ^6.0.0

  #Cache
  shared_preferences: ^2.0.6

  #Core
  provider: ^5.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  get_it: ^7.1.3
  equatable: ^2.0.3
  flutter_dotenv: ^5.0.0
  json_annotation: ^4.0.1

  #Network
  connectivity: ^3.0.6

  #Remote API
  http: ^0.13.3

  #Firebase
  # firebase_core: ^0.5.0
  # firebase_messaging: ^7.0.3
  platform_device_id: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3 #flutter pub run build_runner build
  build_runner: ^2.0.5
  #Core UI
  flutter_native_splash: ^1.1.8+4
  flutter_app_badger: ^1.2.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  #flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  image: assets/launcher/splash.png
  color: "#ffffff"
  fill: true
  #flutter pub run flutter_native_splash:create

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/launcher/
    - lang/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
